spring.application.name=UserAuthService

server.port=8081

# ===============================
# EUREKA CLIENT CONFIG
# ===============================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.enabled=${EUREKA_ENABLED:false}
eureka.client.register-with-eureka=${EUREKA_REGISTER:true}
eureka.client.fetch-registry=${EUREKA_FETCH:true}

# ===============================
# MySQL Database Configuration
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/spring_security_db
spring.datasource.username=root
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===============================
# Feign
# ===============================
feign.circuitbreaker.enabled=true

# ===============================
# JWT
# ===============================
app.jwt.secret=ReplaceWithA256BitSecretKeyForProductionUseOnly123456
app.jwt.expiration-ms=86400000
